[package]
name = "my_shiny_app"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }

[workspace]
members = ["frontend", "backend"]
default-members = ["backend"]
